### ISSUE TITLE
Improve the testimonial section of Home Page

### ISSUE THREAD

**Issue by alphaX86** [pda-mit/PDA-Website#38]
**Description**

For now, we're using the template to show the testimonial section. But in addition to changing content, we need to improve the CSS too.

**Objective**

1. Update contents (need to ask from PDA team side by side)
2. Improve CSS by adding left right buttons, autoscroll etc
3. Add Images of people if any
4. NOTE: We need real feedbacks, so this isn't a template one

**Comment by Thanu0809** [comment]
Assign to me
