### ISSUE TITLE
Design a Contact us section

### ISSUE THREAD

**Issue by coding-geek21** [pda-mit/PDA-Website#74]
**Description**

Design the contact section for PDA website

**Objective**

Contact section should contain 
- Map
- Email , phone number and address 
- Social medias 
- buttons

Files to be edited
- contact.ejs (in views folder)
- and public files (js/css/img  if Neccessary)

**Comment by alphaX86** [comment]
@coding-geek21 would the existing design of contact section suffice or you need a newer look?

**Comment by coding-geek21** [comment]
> @coding-geek21 would the existing design of contact section suffice or you need a newer look?
Anything is fine if it looks good 👍🏼
